#!/usr/bin/env python3
"""Extract the i-quant codebook tables from llama.cpp's ggml-common.h into headers we compile.

Usage:
    python3 scripts/extract_iq_tables.py <path-to-ggml-common.h> src/shainet/native/iq_tables.h

Writes the host header at the given path and the CUDA header alongside it as iq_tables.cuh.

Why a generator instead of checked-in constants typed by hand: these are several thousand hex values
that form part of the format definition, and a single wrong one corrupts weights *silently* -- the
model still loads, still runs, and still produces fluent text. Extraction is self-checking (it counts
the literals and refuses on a mismatch) so a change upstream cannot quietly truncate a table.

llama.cpp is MIT licensed; the tables are reproduced under that licence.
"""
import re
import sys

# (C type, table name, element count, size token as written in the source)
WANT = [
    ("uint8_t", "kmask_iq2xs", 8, "8"),
    ("uint8_t", "ksigns_iq2xs", 128, "128"),
    ("uint64_t", "iq2xxs_grid", 256, "256"),
    ("uint64_t", "iq2xs_grid", 512, "512"),
    ("uint32_t", "iq3xxs_grid", 256, "256"),
    ("uint32_t", "iq3s_grid", 512, "512"),
    ("uint64_t", "iq2s_grid", 1024, "1024"),
    # Declared with a macro as its size rather than a literal.
    ("uint64_t", "iq1s_grid", 2048, "NGRID_IQ1S"),
]

# Every grid a CUDA kernel indexes needs a device copy. That is now all of them: the low-bit tail
# (Q2_K, IQ2_XXS, IQ2_XS, IQ2_S, IQ1_M) is served by native kernels rather than transcoded on the
# CPU, because re-quantizing those weights to symmetric 4-bit measured 194% output error on a
# full-attention block whose sigmoid gate sits near saturation.
#
# Total constant-memory footprint is about 33 KB against CUDA's 64 KB window, dominated by
# iq1s_grid at 16 KB and iq2s_grid at 8 KB.
CU_WANT = [
    ("uint32_t", "iq3xxs_grid", 256),
    ("uint32_t", "iq3s_grid", 512),
    ("uint64_t", "iq2xxs_grid", 256),
    ("uint64_t", "iq2xs_grid", 512),
    ("uint64_t", "iq2s_grid", 1024),
    ("uint64_t", "iq1s_grid", 2048),
    ("uint8_t", "ksigns_iq2xs", 128),
    ("uint8_t", "kmask_iq2xs", 8),
]

HOST_PREAMBLE = [
    "// Generated by scripts/extract_iq_tables.py -- DO NOT EDIT BY HAND.",
    "//",
    "// The i-quant (IQ1_*/IQ2_*/IQ3_*) formats dequantize through codebook lookups rather than a",
    "// plain scale-and-shift, so these tables are part of the format definition rather than an",
    "// optimization. They are extracted verbatim rather than retyped: one wrong constant corrupts",
    "// weights silently, leaving a model that still loads and still sounds fluent.",
    "//",
    "// llama.cpp is MIT licensed; these tables are reproduced under that licence.",
    "",
    "#ifndef SHAINET_IQ_TABLES_H",
    "#define SHAINET_IQ_TABLES_H",
    "",
    "#include <stdint.h>",
    "",
]

CU_PREAMBLE = [
    "// Generated by scripts/extract_iq_tables.py -- DO NOT EDIT BY HAND.",
    "//",
    "// Device-side copies of the i-quant codebook grids. Together they occupy about 33 KB of CUDA's",
    "// 64 KB constant window, dominated by iq1s_grid at 16 KB and iq2s_grid at 8 KB.",
    "//",
    "// They live here as the STAGING SOURCE, not as the array a kernel should index. Constant memory",
    "// has a single broadcast port and is fast only when every lane of a warp reads the SAME address.",
    "// A codebook indexed by packed weight bits is the opposite case -- all 32 lanes want different",
    "// entries -- so indexing these directly from a GEMV serializes the access and was measured at a",
    "// seventh of the bandwidth of the k-quant kernels. A kernel should copy the grid it needs into",
    "// shared memory once per block and index that: 6.4x on IQ3_S, 6.8x on IQ3_XXS. Small codebooks",
    "// are better still as packed register literals, which is what the 16-entry iq4nl table became.",
    "//",
    "// llama.cpp is MIT licensed; these tables are reproduced under that licence.",
    "",
    "#ifndef SHAINET_IQ_TABLES_CUH",
    "#define SHAINET_IQ_TABLES_CUH",
    "",
    "#include <stdint.h>",
    "",
]


def extract(src, ctype, name, size, size_tok):
    pat = r"GGML_TABLE_BEGIN\(\s*%s\s*,\s*%s\s*,\s*%s\s*\)(.*?)GGML_TABLE_END\(\)" % (
        ctype,
        name,
        re.escape(size_tok),
    )
    m = re.search(pat, src, re.S)
    if not m:
        sys.exit("table not found: %s" % name)
    body = m.group(1).strip()
    n = len([t for t in re.split(r"[,\s]+", body) if t and not t.startswith("//")])
    if n != size:
        sys.exit("%s: extracted %d values, expected %d" % (name, n, size))
    return body, n


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    src_path, out_path = sys.argv[1], sys.argv[2]
    src = open(src_path).read()

    host = list(HOST_PREAMBLE)
    bodies = {}
    for ctype, name, size, size_tok in WANT:
        body, n = extract(src, ctype, name, size, size_tok)
        bodies[name] = (ctype, size, body)
        host.append("static const %s shainet_%s[%d] = {" % (ctype, name, size))
        host.append(body)
        host.append("};")
        host.append("")
        print("  %-14s %4d values  ok" % (name, n))
    host.append("#endif // SHAINET_IQ_TABLES_H")
    open(out_path, "w").write("\n".join(host) + "\n")
    print("wrote %s" % out_path)

    cu = list(CU_PREAMBLE)
    for ctype, name, size in CU_WANT:
        _ctype, _size, body = bodies[name]
        cu.append("__device__ __constant__ %s d_%s[%d] = {" % (ctype, name, size))
        cu.append(body)
        cu.append("};")
        cu.append("")
    cu.append("#endif // SHAINET_IQ_TABLES_CUH")
    cu_path = out_path[:-2] + ".cuh" if out_path.endswith(".h") else out_path + ".cuh"
    open(cu_path, "w").write("\n".join(cu) + "\n")
    print("wrote %s" % cu_path)


if __name__ == "__main__":
    main()
