name: Crystal CI

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        crystal: [latest, nightly]
    runs-on: ubuntu-latest

    steps:
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}

      - name: Install basic tools
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl

      - name: Install CUDA libs
        run: |
          # 1. Add the NVIDIA keyring
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-keyring_1.1-1_all.deb
          sudo dpkg -i cuda-keyring_1.1-1_all.deb

          # 2. Update APT
          sudo apt-get update

          # 3. Preconfigure DEBIAN_FRONTEND to suppress prompts
          export DEBIAN_FRONTEND=noninteractive

          # 4. Install CUDA toolkit without interactive prompts
          sudo apt-get -y install cuda-toolkit-12-9

      - name: Download source
        uses: actions/checkout@v6

      - name: Install dependencies
        run: shards install

      - name: Run specs
        run: crystal spec
