name: Crystal CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v3

    - name: Install basic tools
      run: sudo apt-get update && apt-get install -y wget curl
    - name: install CUDA libs
      run: |
        # 1. Add the NVIDIA keyring
        wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-keyring_1.1-1_all.deb
        sudo dpkg -i cuda-keyring_1.1-1_all.deb

        # 2. Update APT
        sudo apt-get update

        # 3. Preconfigure DEBIAN_FRONTEND to suppress prompts
        export DEBIAN_FRONTEND=noninteractive

        # 4. Install CUDA toolkit without interactive prompts
        sudo apt-get -y install cuda-toolkit-12-9
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
